# config
cover: /img/bg_img.jpg
logo: /img/logo.jpg
top_saying:
- title:  我在你的生活中飞<span>奔</span>而过<br />
- content: 不尝试,怎能轻易后悔  
bottom_saying: A goal is a dream with a deadline.
# Content
excerpt_link: Read More

#rss: /atom.xml

highlightjs: vs

#Works
works:
- works_name: AAA
  works_url: /
- works_name: BBB
  works_url: /atom.xml

#duoshuo name
duoshuo: jessicajia

# Miscellaneous
github: https://github.com/
twitter: https://twitter.com/
facebook: https://www.facebook.com/
google: https://google.com/
weibo: http://weibo.com/

#about  timeline
timeline:
- num: 1
  word: 2014/06/12-Start
- num: 2
  word: 2014/11/29-XXX
- num: 3
  word: 2015/02/18-DDD
- num: 4
  word: More

#Links
links:
- name: jessica
  link: http://www.jessicajia.cf/
- name: Name
  link: #